### ISSUE TITLE
Question: Bullet point

### ISSUE THREAD

**Issue by paladox2015** [paladox2015/Metrolook#74]
Should i change it from a squire to a circle. Like vector is a circle. It looks better as a circle because squire is for MonoBook.

**Comment by paladox2015** [comment]
I may add a circle bullet and keep the squire and put the default as a circle and tell you how to change it to a squire if you want.

**Comment by lagleki** [comment]
fine with me

2015-01-11 21:06 GMT+03:00 paladox2015 <notifications@github.com>:

**Comment by paladox2015** [comment]
Ok I will upload circle and keep squire as default.

**Comment by paladox2015** [comment]
Closing this as images added. just that the default stays the same should it kept like a squire or should the new default be circle.
